"""perfiles de jugador y equipo: dorsal, estatus, plantillas, clasificacion, etiqueta de partido

Revision ID: 12f5131375c3
Revises: b4174ec06c01
Create Date: 2026-08-23 10:58:07.357451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f5131375c3'
down_revision: Union[str, Sequence[str], None] = 'b4174ec06c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_standings',
    sa.Column('season_id', sa.String(length=7), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('conference', sa.String(length=10), nullable=True),
    sa.Column('division', sa.String(length=20), nullable=True),
    sa.Column('playoff_rank', sa.SmallInteger(), nullable=True),
    sa.Column('wins', sa.SmallInteger(), nullable=True),
    sa.Column('losses', sa.SmallInteger(), nullable=True),
    sa.Column('win_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('conference_record', sa.String(length=12), nullable=True),
    sa.Column('division_record', sa.String(length=12), nullable=True),
    sa.Column('home_record', sa.String(length=12), nullable=True),
    sa.Column('road_record', sa.String(length=12), nullable=True),
    sa.Column('last_10', sa.String(length=12), nullable=True),
    sa.Column('current_streak', sa.SmallInteger(), nullable=True),
    sa.Column('games_back', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('points_pg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('opp_points_pg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('diff_points_pg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('season_id', 'team_id')
    )
    op.create_index('ix_standings_conf', 'team_standings', ['season_id', 'conference', 'playoff_rank'], unique=False)
    op.create_table('team_season_rosters',
    sa.Column('season_id', sa.String(length=7), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('jersey_number', sa.String(length=4), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('how_acquired', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('season_id', 'team_id', 'player_id')
    )
    op.create_index('ix_roster_player', 'team_season_rosters', ['player_id', 'season_id'], unique=False)
    op.add_column('games', sa.Column('game_label', sa.String(length=60), nullable=True))
    op.add_column('games', sa.Column('game_sublabel', sa.String(length=40), nullable=True))
    op.add_column('players', sa.Column('jersey_number', sa.String(length=4), nullable=True))
    op.add_column('players', sa.Column('roster_status', sa.String(length=20), nullable=True))
    op.add_column('players', sa.Column('season_experience', sa.SmallInteger(), nullable=True))
    op.add_column('players', sa.Column('current_team_id', sa.BigInteger(), nullable=True))
    op.add_column('players', sa.Column('draft_round', sa.SmallInteger(), nullable=True))
    op.add_column('players', sa.Column('draft_number', sa.SmallInteger(), nullable=True))
    op.add_column('players', sa.Column('school', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'players', 'teams', ['current_team_id'], ['team_id'])
    op.add_column('teams', sa.Column('arena', sa.String(length=80), nullable=True))
    op.add_column('teams', sa.Column('arena_capacity', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('owner', sa.String(length=120), nullable=True))
    op.add_column('teams', sa.Column('general_manager', sa.String(length=80), nullable=True))
    op.add_column('teams', sa.Column('head_coach', sa.String(length=80), nullable=True))
    op.add_column('teams', sa.Column('year_founded', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'year_founded')
    op.drop_column('teams', 'head_coach')
    op.drop_column('teams', 'general_manager')
    op.drop_column('teams', 'owner')
    op.drop_column('teams', 'arena_capacity')
    op.drop_column('teams', 'arena')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'school')
    op.drop_column('players', 'draft_number')
    op.drop_column('players', 'draft_round')
    op.drop_column('players', 'current_team_id')
    op.drop_column('players', 'season_experience')
    op.drop_column('players', 'roster_status')
    op.drop_column('players', 'jersey_number')
    op.drop_column('games', 'game_sublabel')
    op.drop_column('games', 'game_label')
    op.drop_index('ix_roster_player', table_name='team_season_rosters')
    op.drop_table('team_season_rosters')
    op.drop_index('ix_standings_conf', table_name='team_standings')
    op.drop_table('team_standings')
    # ### end Alembic commands ###
