"""indice de ausencias de la rotacion

Revision ID: 2612b461266d
Revises: 9e631c83cc16
Create Date: 2026-08-25 23:19:14.645922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2612b461266d'
down_revision: Union[str, Sequence[str], None] = '9e631c83cc16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_game_stats', sa.Column('absent_minutes', sa.Numeric(precision=9, scale=3), nullable=True))
    op.add_column('team_game_stats', sa.Column('absent_players', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_game_stats', 'absent_players')
    op.drop_column('team_game_stats', 'absent_minutes')
    # ### end Alembic commands ###
