"""record con el que se llega al partido

Revision ID: 28f6ffcff139
Revises: 623ac6de8e1b
Create Date: 2026-08-23 23:31:41.519705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f6ffcff139'
down_revision: Union[str, Sequence[str], None] = '623ac6de8e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_game_stats', sa.Column('wins_before', sa.SmallInteger(), nullable=True))
    op.add_column('team_game_stats', sa.Column('losses_before', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_game_stats', 'losses_before')
    op.drop_column('team_game_stats', 'wins_before')
    # ### end Alembic commands ###
