"""de donde salieron los puntos pintura contraataque perdidas

Revision ID: 56f8e1643bab
Revises: 28f6ffcff139
Create Date: 2026-08-25 00:07:06.057910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f8e1643bab'
down_revision: Union[str, Sequence[str], None] = '28f6ffcff139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_game_stats', sa.Column('pts_paint', sa.SmallInteger(), nullable=True))
    op.add_column('team_game_stats', sa.Column('pts_fastbreak', sa.SmallInteger(), nullable=True))
    op.add_column('team_game_stats', sa.Column('pts_off_turnovers', sa.SmallInteger(), nullable=True))
    op.add_column('team_game_stats', sa.Column('pts_2nd_chance', sa.SmallInteger(), nullable=True))
    op.add_column('team_game_stats', sa.Column('opp_pts_paint', sa.SmallInteger(), nullable=True))
    op.add_column('team_game_stats', sa.Column('opp_pts_fastbreak', sa.SmallInteger(), nullable=True))
    op.add_column('team_game_stats', sa.Column('opp_pts_off_turnovers', sa.SmallInteger(), nullable=True))
    op.add_column('team_game_stats', sa.Column('opp_pts_2nd_chance', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_game_stats', 'opp_pts_2nd_chance')
    op.drop_column('team_game_stats', 'opp_pts_off_turnovers')
    op.drop_column('team_game_stats', 'opp_pts_fastbreak')
    op.drop_column('team_game_stats', 'opp_pts_paint')
    op.drop_column('team_game_stats', 'pts_2nd_chance')
    op.drop_column('team_game_stats', 'pts_off_turnovers')
    op.drop_column('team_game_stats', 'pts_fastbreak')
    op.drop_column('team_game_stats', 'pts_paint')
    # ### end Alembic commands ###
