"""ratings de temporada y predicciones

Revision ID: 5af0ce2e823f
Revises: 614356ddd968
Create Date: 2026-08-25 13:21:34.831172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af0ce2e823f'
down_revision: Union[str, Sequence[str], None] = '614356ddd968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_season_ratings',
    sa.Column('season_id', sa.String(length=7), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('offense', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('defense', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('net', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('games', sa.SmallInteger(), nullable=False),
    sa.Column('home_advantage', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('league_mean', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('season_id', 'team_id')
    )
    op.create_table('game_predictions',
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('home_win_prob', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('expected_margin', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('margin_sigma', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('rating_diff', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('rest_diff', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('b2b_diff', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('prob_logit', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('prob_margin', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('train_games', sa.Integer(), nullable=False),
    sa.Column('fitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'model_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_predictions')
    op.drop_table('team_season_ratings')
    # ### end Alembic commands ###
