"""box score de jugador por periodo

Revision ID: 623ac6de8e1b
Revises: a8d8a12f04d7
Create Date: 2026-08-23 22:10:32.659057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623ac6de8e1b'
down_revision: Union[str, Sequence[str], None] = 'a8d8a12f04d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_period_stats',
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.SmallInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('seconds_played', sa.Integer(), nullable=False),
    sa.Column('pts', sa.SmallInteger(), nullable=True),
    sa.Column('fgm', sa.SmallInteger(), nullable=True),
    sa.Column('fga', sa.SmallInteger(), nullable=True),
    sa.Column('fg3m', sa.SmallInteger(), nullable=True),
    sa.Column('fg3a', sa.SmallInteger(), nullable=True),
    sa.Column('ftm', sa.SmallInteger(), nullable=True),
    sa.Column('fta', sa.SmallInteger(), nullable=True),
    sa.Column('oreb', sa.SmallInteger(), nullable=True),
    sa.Column('dreb', sa.SmallInteger(), nullable=True),
    sa.Column('reb', sa.SmallInteger(), nullable=True),
    sa.Column('ast', sa.SmallInteger(), nullable=True),
    sa.Column('stl', sa.SmallInteger(), nullable=True),
    sa.Column('blk', sa.SmallInteger(), nullable=True),
    sa.Column('tov', sa.SmallInteger(), nullable=True),
    sa.Column('pf', sa.SmallInteger(), nullable=True),
    sa.Column('plus_minus', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('period >= 1', name='ck_pps_period_positivo'),
    sa.CheckConstraint('seconds_played >= 0 AND seconds_played <= 900', name='ck_pps_seconds_range'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id', 'period')
    )
    op.create_index('ix_pps_game', 'player_period_stats', ['game_id'], unique=False)
    op.create_index('ix_pps_player_period', 'player_period_stats', ['player_id', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_pps_player_period', table_name='player_period_stats')
    op.drop_index('ix_pps_game', table_name='player_period_stats')
    op.drop_table('player_period_stats')
