"""esquema inicial: dimensiones, hechos e ingest_log

Revision ID: 8077332637e1
Revises: 
Create Date: 2026-08-22 23:36:58.487497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8077332637e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('endpoint', sa.String(length=80), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingest_log_fetched', 'ingest_log', ['fetched_at'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.SmallInteger(), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('draft_year', sa.SmallInteger(), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('from_year', sa.SmallInteger(), nullable=True),
    sa.Column('to_year', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_table('seasons',
    sa.Column('season_id', sa.String(length=7), nullable=False),
    sa.Column('year_start', sa.SmallInteger(), nullable=False),
    sa.Column('year_end', sa.SmallInteger(), nullable=False),
    sa.Column('regular_season_start', sa.Date(), nullable=True),
    sa.Column('regular_season_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.Column('full_name', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('nickname', sa.String(length=60), nullable=True),
    sa.Column('conference', sa.String(length=10), nullable=True),
    sa.Column('division', sa.String(length=20), nullable=True),
    sa.Column('arena_timezone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_teams_abbreviation'), 'teams', ['abbreviation'], unique=False)
    op.create_table('games',
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('season_id', sa.String(length=7), nullable=False),
    sa.Column('season_type', sa.Enum('REGULAR', 'PLAYIN', 'PLAYOFFS', 'PRESEASON', name='season_type'), nullable=False),
    sa.Column('game_date_local', sa.Date(), nullable=False),
    sa.Column('tipoff_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.BigInteger(), nullable=False),
    sa.Column('away_team_id', sa.BigInteger(), nullable=False),
    sa.Column('home_pts', sa.SmallInteger(), nullable=True),
    sa.Column('away_pts', sa.SmallInteger(), nullable=True),
    sa.Column('ot_periods', sa.SmallInteger(), nullable=False),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('arena_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index('ix_games_away_team', 'games', ['away_team_id', 'game_date_local'], unique=False)
    op.create_index('ix_games_date', 'games', ['game_date_local'], unique=False)
    op.create_index('ix_games_home_team', 'games', ['home_team_id', 'game_date_local'], unique=False)
    op.create_index('ix_games_season_date', 'games', ['season_id', 'game_date_local'], unique=False)
    op.create_index(op.f('ix_games_season_id'), 'games', ['season_id'], unique=False)
    op.create_index(op.f('ix_games_season_type'), 'games', ['season_type'], unique=False)
    op.create_table('player_game_advanced',
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('ts_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('efg_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('usg_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ast_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('reb_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('oreb_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('dreb_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('tov_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('off_rating', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('def_rating', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('net_rating', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('pace', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('pie', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_index('ix_pga_player_game', 'player_game_advanced', ['player_id', 'game_id'], unique=False)
    op.create_table('player_game_stats',
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('seconds_played', sa.Integer(), nullable=False),
    sa.Column('dnp_reason', sa.Text(), nullable=True),
    sa.Column('pts', sa.SmallInteger(), nullable=True),
    sa.Column('fgm', sa.SmallInteger(), nullable=True),
    sa.Column('fga', sa.SmallInteger(), nullable=True),
    sa.Column('fg3m', sa.SmallInteger(), nullable=True),
    sa.Column('fg3a', sa.SmallInteger(), nullable=True),
    sa.Column('ftm', sa.SmallInteger(), nullable=True),
    sa.Column('fta', sa.SmallInteger(), nullable=True),
    sa.Column('oreb', sa.SmallInteger(), nullable=True),
    sa.Column('dreb', sa.SmallInteger(), nullable=True),
    sa.Column('reb', sa.SmallInteger(), nullable=True),
    sa.Column('ast', sa.SmallInteger(), nullable=True),
    sa.Column('stl', sa.SmallInteger(), nullable=True),
    sa.Column('blk', sa.SmallInteger(), nullable=True),
    sa.Column('tov', sa.SmallInteger(), nullable=True),
    sa.Column('pf', sa.SmallInteger(), nullable=True),
    sa.Column('plus_minus', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('seconds_played >= 0 AND seconds_played <= 4800', name='ck_pgs_seconds_range'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_index('ix_pgs_player_game', 'player_game_stats', ['player_id', 'game_id'], unique=False)
    op.create_index('ix_pgs_team', 'player_game_stats', ['team_id'], unique=False)
    op.create_table('team_game_stats',
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('opponent_team_id', sa.BigInteger(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('seconds_played', sa.Integer(), nullable=True),
    sa.Column('pts', sa.SmallInteger(), nullable=True),
    sa.Column('fgm', sa.SmallInteger(), nullable=True),
    sa.Column('fga', sa.SmallInteger(), nullable=True),
    sa.Column('fg3m', sa.SmallInteger(), nullable=True),
    sa.Column('fg3a', sa.SmallInteger(), nullable=True),
    sa.Column('ftm', sa.SmallInteger(), nullable=True),
    sa.Column('fta', sa.SmallInteger(), nullable=True),
    sa.Column('oreb', sa.SmallInteger(), nullable=True),
    sa.Column('dreb', sa.SmallInteger(), nullable=True),
    sa.Column('reb', sa.SmallInteger(), nullable=True),
    sa.Column('ast', sa.SmallInteger(), nullable=True),
    sa.Column('stl', sa.SmallInteger(), nullable=True),
    sa.Column('blk', sa.SmallInteger(), nullable=True),
    sa.Column('tov', sa.SmallInteger(), nullable=True),
    sa.Column('pf', sa.SmallInteger(), nullable=True),
    sa.Column('plus_minus', sa.SmallInteger(), nullable=True),
    sa.Column('possessions', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('pace', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('off_rating', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('def_rating', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('net_rating', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('efg_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ts_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('rest_days', sa.SmallInteger(), nullable=True),
    sa.Column('is_back_to_back', sa.Boolean(), nullable=True),
    sa.CheckConstraint('seconds_played >= 0', name='ck_tgs_seconds_nonneg'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'team_id')
    )
    op.create_index('ix_tgs_team_game', 'team_game_stats', ['team_id', 'game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tgs_team_game', table_name='team_game_stats')
    op.drop_table('team_game_stats')
    op.drop_index('ix_pgs_team', table_name='player_game_stats')
    op.drop_index('ix_pgs_player_game', table_name='player_game_stats')
    op.drop_table('player_game_stats')
    op.drop_index('ix_pga_player_game', table_name='player_game_advanced')
    op.drop_table('player_game_advanced')
    op.drop_index(op.f('ix_games_season_type'), table_name='games')
    op.drop_index(op.f('ix_games_season_id'), table_name='games')
    op.drop_index('ix_games_season_date', table_name='games')
    op.drop_index('ix_games_home_team', table_name='games')
    op.drop_index('ix_games_date', table_name='games')
    op.drop_index('ix_games_away_team', table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_abbreviation'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_table('players')
    op.drop_index('ix_ingest_log_fetched', table_name='ingest_log')
    op.drop_table('ingest_log')
    # ### end Alembic commands ###
