"""play by play

Revision ID: 85c21923449f
Revises: 56f8e1643bab
Create Date: 2026-08-25 00:16:18.205954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c21923449f'
down_revision: Union[str, Sequence[str], None] = '56f8e1643bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_by_play',
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('action_number', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.SmallInteger(), nullable=False),
    sa.Column('clock_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('elapsed_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=True),
    sa.Column('sub_type', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('score_home', sa.SmallInteger(), nullable=True),
    sa.Column('score_away', sa.SmallInteger(), nullable=True),
    sa.Column('is_field_goal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('shot_result', sa.Boolean(), nullable=True),
    sa.Column('shot_value', sa.SmallInteger(), nullable=True),
    sa.Column('shot_distance', sa.SmallInteger(), nullable=True),
    sa.Column('x_legacy', sa.SmallInteger(), nullable=True),
    sa.Column('y_legacy', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('period >= 1', name='ck_pbp_period_positivo'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'action_number')
    )
    op.create_index('ix_pbp_tiros', 'play_by_play', ['player_id', 'shot_result'], unique=False, postgresql_where=sa.text('is_field_goal'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pbp_tiros', table_name='play_by_play', postgresql_where=sa.text('is_field_goal'))
    op.drop_table('play_by_play')
    # ### end Alembic commands ###
