"""coeficientes del modelo de pronostico

Revision ID: 9e631c83cc16
Revises: 5af0ce2e823f
Create Date: 2026-08-25 17:39:20.704516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e631c83cc16'
down_revision: Union[str, Sequence[str], None] = '5af0ce2e823f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('season_id', sa.String(length=7), nullable=False),
    sa.Column('logit_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('margin_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sigma', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('train_games', sa.Integer(), nullable=False),
    sa.Column('fitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('model_version', 'season_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_runs')
    # ### end Alembic commands ###
