"""marcador por periodo y arbitros del partido

Revision ID: a8d8a12f04d7
Revises: 12f5131375c3
Create Date: 2026-08-23 21:56:24.442434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d8a12f04d7'
down_revision: Union[str, Sequence[str], None] = '12f5131375c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_officials',
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('official_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('jersey_number', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'official_id')
    )
    op.create_table('game_period_scores',
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.SmallInteger(), nullable=False),
    sa.Column('points', sa.SmallInteger(), nullable=False),
    sa.Column('is_overtime', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('period >= 1', name='ck_gps_period_positivo'),
    sa.CheckConstraint('points >= 0', name='ck_gps_points_nonneg'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'team_id', 'period')
    )
    op.create_index('ix_gps_game', 'game_period_scores', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gps_game', table_name='game_period_scores')
    op.drop_table('game_period_scores')
    op.drop_table('game_officials')
    # ### end Alembic commands ###
